# Stubs for antlr4.tree.Chunk (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class Chunk: ...

class TagChunk(Chunk):
    tag = ...  # type: Any
    label = ...  # type: Any
    def __init__(self, tag, label: Optional[Any] = ...) -> None: ...

class TextChunk(Chunk):
    text = ...  # type: Any
    def __init__(self, text) -> None: ...
