# Stubs for antlr4.tree.ParseTreePattern (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class ParseTreePattern:
    matcher = ...  # type: Any
    patternRuleIndex = ...  # type: Any
    pattern = ...  # type: Any
    patternTree = ...  # type: Any
    def __init__(self, matcher, pattern, patternRuleIndex, patternTree) -> None: ...
    def match(self, tree): ...
    def matches(self, tree): ...
    def findAll(self, tree, xpath): ...
