# Stubs for antlr4.tree.RuleTagToken (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from antlr4.Token import Token

class RuleTagToken(Token):
    source = ...  # type: Any
    type = ...  # type: Any
    channel = ...  # type: Any
    start = ...  # type: int
    stop = ...  # type: int
    tokenIndex = ...  # type: int
    line = ...  # type: int
    column = ...  # type: int
    label = ...  # type: Any
    ruleName = ...  # type: Any
    def __init__(self, ruleName, bypassTokenType, label: Optional[Any] = ...) -> None: ...
    def getText(self): ...
