# Stubs for antlr4.tree.TokenTagToken (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from antlr4.Token import CommonToken

class TokenTagToken(CommonToken):
    tokenName = ...  # type: Any
    label = ...  # type: Any
    def __init__(self, tokenName, type, label: Optional[Any] = ...) -> None: ...
    def getText(self): ...
