# Stubs for antlr4.atn.ATNDeserializationOptions (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

ATNDeserializationOptions = ...  # type: Any

class ATNDeserializationOptions:
    defaultOptions = ...  # type: Any
    readOnly = ...  # type: bool
    verifyATN = ...  # type: Any
    generateRuleBypassTransitions = ...  # type: Any
    def __init__(self, copyFrom: Optional[Any] = ...) -> None: ...
    def __setattr__(self, key, value): ...
