# Stubs for antlr4.atn.ATNSimulator (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class ATNSimulator:
    ERROR = ...  # type: Any
    atn = ...  # type: Any
    sharedContextCache = ...  # type: Any
    def __init__(self, atn, sharedContextCache) -> None: ...
    def getCachedContext(self, context): ...
