# Stubs for antlr4.atn.ATNType (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from enum import IntEnum

class ATNType(IntEnum):
    LEXER = ...  # type: int
    PARSER = ...  # type: int
    @classmethod
    def fromOrdinal(cls, i): ...
