# Stubs for antlr4.CommonTokenFactory (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class TokenFactory: ...

class CommonTokenFactory(TokenFactory):
    DEFAULT = ...  # type: Any
    copyText = ...  # type: Any
    def __init__(self, copyText: bool = ...) -> None: ...
    def create(self, source, type, text, channel, start, stop, line, column): ...
    def createThin(self, type, text): ...
