# Stubs for antlr4.FileStream (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import unittest
from antlr4.InputStream import InputStream

class FileStream(InputStream):
    fileName = ...  # type: Any
    def __init__(self, fileName, encoding: str = ...) -> None: ...
    def readDataFrom(self, fileName, encoding): ...

class TestFileStream(unittest.TestCase):
    def testStream(self): ...
