# Stubs for antlr4.ListTokenSource (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from antlr4.Lexer import TokenSource

class ListTokenSource(TokenSource):
    tokens = ...  # type: Any
    sourceName = ...  # type: Any
    pos = ...  # type: int
    eofToken = ...  # type: Any
    def __init__(self, tokens, sourceName: Optional[Any] = ...) -> None: ...
    @property
    def column(self): ...
    def nextToken(self): ...
    @property
    def line(self): ...
    def getInputStream(self): ...
    def getSourceName(self): ...
