# Stubs for antlr4.LL1Analyzer (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class LL1Analyzer:
    HIT_PRED = ...  # type: Any
    atn = ...  # type: Any
    def __init__(self, atn) -> None: ...
    def getDecisionLookahead(self, s): ...
    def LOOK(self, s, stopState: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
