# Stubs for antlr4.dfa.DFAState (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class PredPrediction:
    alt = ...  # type: Any
    pred = ...  # type: Any
    def __init__(self, pred, alt) -> None: ...

class DFAState:
    stateNumber = ...  # type: Any
    configs = ...  # type: Any
    edges = ...  # type: Any
    isAcceptState = ...  # type: bool
    prediction = ...  # type: int
    lexerActionExecutor = ...  # type: Any
    requiresFullContext = ...  # type: bool
    predicates = ...  # type: Any
    def __init__(self, stateNumber: int = ..., configs: Any = ...) -> None: ...
    def getAltSet(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
