# Stubs for antlr4.dfa.DFASerializer (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class DFASerializer:
    dfa = ...  # type: Any
    literalNames = ...  # type: Any
    symbolicNames = ...  # type: Any
    def __init__(self, dfa, literalNames: Optional[Any] = ..., symbolicNames: Optional[Any] = ...) -> None: ...
    def getEdgeLabel(self, i): ...
    def getStateString(self, s): ...

class LexerDFASerializer(DFASerializer):
    def __init__(self, dfa) -> None: ...
    def getEdgeLabel(self, i): ...
