#begin
-- some difficult recursive queries
select *, sqrt(a), lower(substring(str, 'a', length(str)/2)) as col3 from tab1 where a is not \N;

select * from (((((((select col1 from t1) as ttt))))));

SELECT 
F_FORUM.*, F.FORUM_GROUP_ID, F.NAME, F.DESCRIPTION, F.SORT, F.ACTIVE, F.ALLOW_HTML, F.ALLOW_ANCHOR, F.ALLOW_BIU, F.ALLOW_IMG, 
F.ALLOW_VIDEO, F.ALLOW_LIST, F.ALLOW_QUOTE, F.ALLOW_CODE, F.ALLOW_FONT, F.ALLOW_SMILES, F.ALLOW_ALIGN, F.ALLOW_UPLOAD, F.ALLOW_UPLOAD_EXT, 
F.ALLOW_MOVE_TOPIC, F.ALLOW_NL2BR, F.ALLOW_TABLE,  F.ALLOW_TOPIC_TITLED, F.ALLOW_SIGNATURE, F.ASK_GUEST_EMAIL, F.USE_CAPTCHA, F.MODERATION, 
F.INDEXATION, F.DEDUPLICATION, F.ORDER_BY, F.ORDER_DIRECTION, '' as LID, '' as DIR, F.TOPICS, F.XML_ID, F.POSTS, F.LAST_POSTER_ID, F.LAST_POSTER_NAME, 
DATE_FORMAT(F.LAST_POST_DATE, '%d.%m.%Y %H:%i:%s') as LAST_POST_DATE, F.LAST_MESSAGE_ID, FM.TOPIC_ID as TID, F.LAST_MESSAGE_ID as MID, F.POSTS_UNAPPROVED, 
F.ABS_LAST_POSTER_ID, F.ABS_LAST_POSTER_NAME, DATE_FORMAT(F.ABS_LAST_POST_DATE, '%d.%m.%Y %H:%i:%s') as ABS_LAST_POST_DATE, F.ABS_LAST_MESSAGE_ID, 
FM_ABS.TOPIC_ID as ABS_TID, F.EVENT1, F.EVENT2, F.EVENT3, FT.TITLE, FT.SOCNET_GROUP_ID, FT.OWNER_ID, FT.HTML AS TOPIC_HTML, FM.PARAM1, FM.PARAM2, 
FT_ABS.TITLE as ABS_TITLE, FT_ABS.SOCNET_GROUP_ID as ABS_SOCNET_GROUP_ID, FT_ABS.OWNER_ID as ABS_OWNER_ID, FT_ABS.HTML AS ABS_TOPIC_HTML, 
FM_ABS.PARAM1 as ABS_PARAM1, FM_ABS.PARAM2 as ABS_PARAM2, F.HTML 
FROM 
	( 
		SELECT F.ID , F2S.PATH2FORUM_MESSAGE 
		FROM 
			b_forum F 
			INNER JOIN b_forum2site F2S ON (F2S.FORUM_ID=F.ID) 
		WHERE (1=1  AND ((F2S.SITE_ID = 's1')) AND ((F.ID IN (1, 2))) ) 
		GROUP BY F.ID,F2S.PATH2FORUM_MESSAGE 
	) F_FORUM INNER JOIN b_forum F ON (F_FORUM.ID = F.ID) 
	LEFT JOIN b_forum_group FG ON F.FORUM_GROUP_ID = FG.ID 
	LEFT JOIN b_forum_message FM ON F.LAST_MESSAGE_ID = FM.ID 
	LEFT JOIN b_forum_topic FT ON FM.TOPIC_ID = FT.ID 
	LEFT JOIN b_forum_message FM_ABS ON F.ABS_LAST_MESSAGE_ID = FM_ABS.ID 
	LEFT JOIN b_forum_topic FT_ABS ON FM_ABS.TOPIC_ID = FT_ABS.ID;

SELECT 
FST.*, FU.*, FSTAT.IP_ADDRESS, FSTAT.PHPSESSID,  DATE_FORMAT(FSTAT.LAST_VISIT, '%d.%m.%Y %H:%i:%s') AS LAST_VISIT,  FSTAT.FORUM_ID, FSTAT.TOPIC_ID,  
U.LOGIN, U.NAME, U.SECOND_NAME, U.LAST_NAME,  FSTAT.SHOW_NAME 
FROM 
	(  
		SELECT FSTAT.USER_ID, MAX(FSTAT.ID) FST_ID, COUNT(FSTAT.PHPSESSID) COUNT_USER  
		FROM 
			b_forum_stat FSTAT 
			LEFT JOIN b_user U ON (FSTAT.USER_ID=U.ID) 
		WHERE 1=1  AND (FSTAT.SITE_ID = 's1') AND (FSTAT.USER_ID = 0 OR U.ACTIVE = 'Y') AND (FROM_UNIXTIME(UNIX_TIMESTAMP(CURRENT_TIMESTAMP) - 600) <=  FSTAT.LAST_VISIT)  
		GROUP BY FSTAT.USER_ID
	) FST 
	LEFT JOIN b_forum_stat FSTAT ON (FST.FST_ID = FSTAT.ID) 
	LEFT JOIN b_forum_user FU ON (FST.USER_ID = FU.USER_ID) 
	LEFT JOIN b_user U ON (FST.USER_ID = U.ID)  
ORDER BY FSTAT.USER_ID DESC;
#end
